# Generated by Django 4.0.3 on 2022-04-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BossUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('firsname', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoriToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('is_boss', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('firsname', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bossuser')),
            ],
        ),
    ]
